#NearPlus ~ Created by PimpDuck#
#Cooldown is in minutes#

NearPlus:
  Chat-Prefix: ' &f[&bNear&4Plus&f] '
  ServerName: ' Server name here '
  Distance:
    God: 175
    Ub3r: 150
    Legend: 125
    Super: 100

  Options:
    Cooldown: 6
